version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - wb_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  celery-worker:
    build: ../
    command: celery -A goods.tasks:celery worker --loglevel=INFO
    volumes:
      - wb_celery:/app
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

  celery-beat:
    build:  ../
    command: celery -A goods.tasks:celery beat --loglevel=INFO 
    depends_on:
      - redis
      - db
      - celery-worker
    env_file:
      - ./.env

  flower:
    build:  ../
    command: celery -A goods.tasks:celery flower --port=5555
    ports:
      - 5555:5555
    depends_on:
      - celery-worker
    env_file:
      - ./.env

  backend:
    build: ../
    restart: always
    ports:
    - "8000:8000"
    volumes:
      - wb_back:/app
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

volumes:
  wb_back:
  wb_db:
  wb_celery: