"""empty message

Revision ID: 3da558d6fd9a
Revises: 01498111f053
Create Date: 2023-04-19 23:03:40.068915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da558d6fd9a'
down_revision = '01498111f053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'colors',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'colors',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
