"""empty message

Revision ID: f432683c32f4
Revises: 3da558d6fd9a
Create Date: 2023-04-20 11:02:15.964659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f432683c32f4'
down_revision = '3da558d6fd9a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('last_upd', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'last_upd')
    # ### end Alembic commands ###
